INSERT INTO url_validator_configs (type, protocols, domains, extensions, created_at, updated_at)
VALUES
    -- IMAGES
    (
        'image',
        ARRAY[
            'https'
        ],
        ARRAY[
            'i.imgur.com',
            'imgur.com',
            'image.ibb.co',
            'i.reddit.it',
            'cdn.discordapp.com',
            'media.discordapp.net',
            'images-ext-2.discordapp.net',
            'i.reddit.it',
            'gyazo.com',
            'puu.sh',
            'i.postimg.cc',
            'deviantart.com',
            'photobucket.com',
            's1.ax1x.com',
            's27.postimg.io',
            '1.bp.blogspot.com',
            'tiebapic.baidu.com',
            's25.postimg.gg',
            'aotcorehome.files.wordpress.com',
            'imgse.com',
            'raw.githubusercontent.com'
        ],
        ARRAY[
        '.jpg',
        '.png',
        '.jpeg'
        ],
        now(),
        now()
    ),
    -- TEXT
   (
        'text',
        ARRAY[
            'https'
        ],
        ARRAY[
            'pastebin.com',
            'dropbox.com',
            'cdn.discordapp.com',
            'media.discordapp.net',
            'raw.githubusercontent.com'
        ],
        ARRAY[
            '.txt',
            '.acl'
        ],
        now(),
        now()
    ),
    -- ASSET BUNDLE
   (
        'asset_bundle',
        ARRAY[
            'https'
        ],
        ARRAY[
            'dropbox.com',
            'cdn.discordapp.com',
            'media.discordapp.net',
            'raw.githubusercontent.com'
        ],
        ARRAY[
        ''
        ],
        now(),
        now()
    );
